var Base_CreatureList = {
	// Awaken spel creations
	"awakened shrub": {
		name: "Awakened Shrub",
		nameThis: "shrub",
		source: [["SRD24", 260], ["M24", 23]],
		size: 4,
		type: "Plant",
		alignment: "Neutral",
		ac: 9,
		hp: 10,
		hd: [3, 6],
		speed: "20 ft",
		scores: [3, 8, 11, 10, 10, 6],
		vulnerabilities: "Fire",
		resistances: "Piercing",
		passivePerception: 10,
		languages: "Common plus one other language",
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Rake",
			ability: 2,
			damage: [1, "", "slashing"],
			range: "Melee (5 ft)",
			abilitytodamage: false,
		}],
	},
	"awakened tree": {
		name: "Awakened Tree",
		nameThis: "tree",
		source: [["SRD24", 260], ["M24", 23]],
		size: 1,
		type: "Plant",
		alignment: "Neutral",
		ac: 13,
		hp: 59,
		hd: [7, 12],
		speed: "20 ft",
		scores: [19, 6, 15, 10, 10, 7],
		vulnerabilities: "Fire",
		resistances: "Bludgeoning, Piercing",
		passivePerception: 10,
		languages: "Common plus one other language",
		challengeRating: "2",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Slam",
			ability: 1,
			damage: [2, 8, "bludgeoning"],
			range: "Melee (10 ft)",
		}],
	},
	// Pact of the Chain familiars
	"imp": {
		name: "Imp",
		source: [["SRD24", 300], ["M24", 177]],
		size: 5,
		type: "Fiend",
		subtype: "Devil",
		companion: ["pact_of_the_chain"],
		alignment: "Lawful Evil",
		ac: 13,
		hp: 21,
		hd: [6, 4],
		speed: "20 ft, fly 40 ft",
		scores: [6, 17, 13, 11, 12, 14],
		skills: {
			"deception": 4,
			"insight": 3,
			"stealth": 5,
		},
		resistances: "Cold",
		immunities: "Fire, Poison; Poisoned",
		senses: "Darkvision 120 ft (unimpeded by magical Darkness)",
		passivePerception: 11,
		languages: "Common, Infernal",
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 1,
		features: [{
			name: "Magic Resistance",
			description: "The [THIS] has Advantage on saves against spells and magical effects.",
		}],
		actions: [{
			name: "Invisibility",
			description: "As an Action, the [THIS] can cast Invisibility on itself, requiring no spell components and using Charisma as the spellcasting ability.",
		}, {
			name: "Shape-Shift",
			description: "As an Action, the [THIS] can shape-shift to resemble a rat (Speed 20 ft), a raven (20 ft, Fly 60 ft), or a spider (20 ft, Climb 20 ft), or return to its true form. Its statistics are the same in each form, except for its Speed. Any equipment it is wearing or carrying isn't transformed.",
		}],
		attacks: [{
			name: "Sting",
			ability: 2,
			damage: [1, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "+2d6 Poison damage",
		}],
	},
	"pseudodragon": {
		name: "Pseudodragon",
		nameThis: "dragon",
		source: [["SRD24", 316], ["M24", 249]],
		size: 5,
		type: "Dragon",
		companion: ["pact_of_the_chain"],
		alignment: "Neutral Good",
		ac: 14,
		hp: 10,
		hd: [3, 4],
		speed: "15 ft, fly 60 ft",
		scores: [6, 15, 13, 10, 12, 10],
		skills: {
			"perception": 5,
			"stealth": 4,
		},
		senses: "Blindsight 10 ft, Darkvision 60 ft",
		passivePerception: 15,
		languages: "Understands Common and Draconic but can't speak",
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 2,
		features: [{
			name: "Magic Resistance",
			description: "The [THIS] has Advantage on saves against spells and magical effects.",
		}],
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Bite attacks.",
		}, {
			name: "Sting",
			description: "As an Action, the [THIS] can sting one creature it can see within 5 ft. It must make a Constitution save or take 2d4 Poison damage and " + (typePF ? "be Poisoned" : "have the Poisoned condition") + " for 1 hour. While Poisoned, the target also has the Unconscious condition, which ends early if the target takes damage or a creature within 5 ft of it takes an action to wake it.",
		}],
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, 4, "piercing"],
			range: "Melee (5 ft)",
			description: "Two Bite attacks as an Action",
		}, {
			name: "Sting",
			ability: 2,
			damage: [2, 4, "poison"],
			range: "5 ft",
			description: "Con save to avoid; Also Poisoned for 1 hour; Unconscious while Poisoned (see Sting)",
			dc: true,
			abilitytodamage: false,
		}],
	},
	"quasit": {
		name: "Quasit",
		source: [["SRD24", 317], ["M24", 252]],
		size: 5,
		type: "Fiend",
		subtype: "Demon",
		companion: ["pact_of_the_chain"],
		alignment: "Chaotic Evil",
		ac: 13,
		hp: 25,
		hd: [10, 4],
		speed: "40 ft",
		scores: [5, 17, 10, 7, 10, 10],
		skills: {
			"stealth": 5,
		},
		resistances: "Cold, Fire, Lightning",
		immunities: "Poison; Poisoned",
		senses: "Darkvision 120 ft",
		passivePerception: 10,
		languages: "Abyssal, Common",
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 1,
		features: [{
			name: "Magic Resistance",
			description: "The [THIS] has Advantage on saves against spells and magical effects.",
		}],
		actions: [{
			name: "Invisibility",
			description: "As an Action, the [THIS] can cast Invisibility on itself, requiring no spell components and using Charisma as the spellcasting ability.",
		}, {
			name: "Scare (1/Day)",
			description: "As an Action, the [THIS] can scare one creature it can see within 20 ft. It must make on a Wisdom save or have the Frightened condition. At the end of each of its turns, it can repeat the save to end the effect. After 1 minute, it succeeds automatically.",
		}, {
			name: "Shape-Shift",
			description: "As an Action, the [THIS] can shape-shift to resemble a bat (Speed 10 ft, Fly 40 ft), a centipede (40 ft, Climb 40 ft), or a toad (40 ft, Swim 40 ft), or return to its true form. Its statistics are the same in each form, except for its Speed. Any equipment it is wearing or carrying isn't transformed.",
		}],
		attacks: [{
			name: "Rend",
			ability: 2,
			damage: [1, 4, "slashing"],
			range: "Melee (5 ft)",
			description: "Poisoned until the quasit's next turn starts",
		}, {
			name: "Scare (1/Day)",
			ability: 3,
			damage: ["Wis save", "", "Frightened"],
			range: "20 ft",
			description: "Lasts 1 min; Target repeats save at end of turn",
			dc: true,
		}],
	},
	"skeleton": {
		name: "Skeleton",
		nameAlt: ["Humanoid Skeleton", "Skeleton, Humanoid"],
		nameThis: "skeleton",
		source: [["SRD24", 325], ["M24", 282]],
		size: 3,
		type: "Undead",
		companion: ["pact_of_the_chain"],
		alignment: "Lawful Evil",
		ac: 14,
		hp: 13,
		hd: [2, 8],
		speed: "30 ft",
		scores: [10, 16, 15, 6, 8, 5],
		vulnerabilities: "Bludgeoning",
		immunities: "Poison; Exhaustion, Poisoned",
		senses: "Darkvision 60 ft",
		passivePerception: 9,
		languages: "Understands Common plus one other language but can't speak",
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Shortsword",
			ability: 2,
			damage: [1, 6, "piercing"],
			range: "Melee (5 ft)",
		}, {
			name: "Shortbow",
			ability: 2,
			damage: [1, 6, "piercing"],
			range: "80/320 ft",
		}],
	},
	"sphinx of wonder": {
		name: "Sphinx of Wonder",
		nameThis: "sphinx",
		source: [["SRD24", 327], ["M24", 291]],
		size: 5,
		type: "Celestial",
		companion: ["pact_of_the_chain"],
		alignment: "Lawful Good",
		ac: 13,
		hp: 24,
		hd: [7, 4],
		speed: "20 ft, fly 40 ft",
		scores: [6, 17, 13, 15, 12, 11],
		skills: {
			"arcana": 4,
			"religion": 4,
			"stealth": 5,
		},
		resistances: "Necrotic, Psychic, Radiant",
		senses: "Darkvision 60 ft",
		passivePerception: 11,
		languages: "Celestial, Common",
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 1,
		features: [{
			name: "Magic Resistance",
			description: "The [THIS] has Advantage on saves against spells and magical effects.",
		}],
		actions: [{
			name: "Burst of Ingenuity (2/Day)",
			description: "As a Reaction when the [THIS] or another creature within 30 ft makes an ability check or saving throw, the [THIS] can add 2 to the roll.",
		}],
		attacks: [{
			name: "Rend",
			ability: 2,
			damage: [1, 4, "slashing"],
			range: "Melee (5 ft)",
			description: "+2d6 Radiant damage",
		}],
	},
	"sprite": {
		name: "Sprite",
		source: [["SRD24", 329], ["M24", 298]],
		size: 5,
		type: "Fey",
		companion: ["pact_of_the_chain"],
		alignment: "Neutral Good",
		ac: 15,
		hp: 10,
		hd: [4, 4],
		speed: "10 ft, fly 40 ft",
		scores: [3, 18, 10, 14, 13, 11],
		skills: {
			"perception": 3,
			"stealth": 8,
		},
		passivePerception: 13,
		languages: "Common, Elvish, Sylvan",
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Invisibility",
			description: "As an Action, the [THIS] can cast Invisibility on itself, requiring no spell components and using Charisma as the spellcasting ability.",
		}, {
			name: "Heart Sight",
			description: "As an Action, the [THIS] can sense the innate goodness of one creature it can see within 5 ft. It must make a Charisma save (Celestials, Fiends, and Undead automatically fail) or the [THIS] knows the target's emotions and alignment.",
		}],
		attacks: [{
			name: "Needle Sword",
			ability: 2,
			damage: [1, 4, "piercing"],
			range: "Melee (5 ft)",
		}, {
			name: "Enchanting Bow",
			ability: 2,
			damage: [1, "", "piercing"],
			range: "40/160 ft",
			description: "Target is Charmed until the Sprite's next turn starts",
			abilitytodamage: false,
		}, {
			name: "Heart Sight",
			ability: 3,
			damage: ["Cha save", "", "Knowledge"],
			range: "5 ft",
			description: "Sprite knows the target's emotions and alignment; Celestial/Fiend/Undead auto-fail save",
			dc: true,
		}],
	},
	// Undead (Skeleton is included with Pact of the Chain familiars)
	"warhorse skeleton": {
		name: "Warhorse Skeleton",
		nameAlt: ["Skeleton, Warhorse"],
		nameThis: "skeleton",
		source: [["SRD24", 326], ["M24", 282]],
		size: 2,
		type: "Undead",
		alignment: "Lawful Evil",
		ac: 13,
		hp: 22,
		hd: [3, 10],
		speed: "60 ft",
		scores: [18, 12, 15, 2, 8, 5],
		vulnerabilities: "Bludgeoning",
		immunities: "Poison; Exhaustion, Poisoned",
		senses: "Darkvision 60 ft",
		passivePerception: 9,
		challengeRating: "1/2",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Hooves",
			description: "If the target is a Large or smaller creature and the [THIS] moved at least 20 ft straight toward it immediately before the hit, the target has the Prone condition.",
		}],
		attacks: [{
			name: "Hooves",
			ability: 1,
			damage: [1, 6, "bludgeoning"],
			range: "Melee (5 ft)",
			description: "If moved 20 ft and hit \u2264Large: knocked Prone",
		}],
	},
	"zombie": {
		name: "Zombie",
		source: [["SRD24", 343], ["M24", 346]],
		size: 3,
		type: "Undead",
		alignment: "Neutral Evil",
		ac: 8,
		hp: 15,
		hd: [2, 8],
		speed: "20 ft",
		scores: [13, 6, 16, 3, 6, 5],
		saves: ["", "", "", "", 0, ""],
		immunities: "Poison; Exhaustion, Poisoned",
		senses: "Darkvision 60 ft",
		passivePerception: 8,
		languages: "Understands Common plus one other language but can't speak",
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Undead Fortitude",
			description: "If damage reduces the [THIS] to 0 HP, it makes a Constitution save (DC 5 + damage taken) unless the damage is Radiant or from a Critical Hit. *Success:* the [THIS] drops to 1 HP instead.",
		}],
		attacks: [{
			name: "Slam",
			ability: 1,
			damage: [1, 8, "bludgeoning"],
			range: "Melee (5 ft)",
		}],
	},
	"ogre zombie": {
		name: "Ogre Zombie",
		nameAlt: ["Zombie, Ogre"],
		nameThis: "zombie",
		source: [["SRD24", 344], ["M24", 346]],
		size: 2,
		type: "Undead",
		alignment: "Neutral Evil",
		ac: 8,
		hp: 85,
		hd: [9, 10],
		speed: "30 ft",
		scores: [19, 6, 18, 3, 6, 5],
		saves: ["", "", "", "", 0, ""],
		immunities: "Poison; Exhaustion, Poisoned",
		senses: "Darkvision 60 ft",
		passivePerception: 8,
		languages: "Understands Common and Giant but can't speak",
		challengeRating: "2",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Undead Fortitude",
			description: "If damage reduces the [THIS] to 0 HP, it makes a Constitution save (DC 5 + damage taken) unless the damage is Radiant or from a Critical Hit. *Success:* the [THIS] drops to 1 HP instead.",
		}],
		attacks: [{
			name: "Slam",
			ability: 1,
			damage: [2, 8, "bludgeoning"],
			range: "Melee (5 ft)",
		}],
	},
	// Other Likely Familiar Options (but not RAW)
	"flying snake": {
		name: "Flying Snake",
		nameAlt: ["Snake, Flying"],
		nameThis: "snake",
		source: [["SRD24", 348], ["M24", 353]],
		size: 5,
		type: "Monstrosity",
		alignment: "Unaligned",
		ac: 14,
		hp: 5,
		hd: [2, 4],
		speed: "30 ft, fly 60 ft, swim 30 ft",
		scores: [4, 15, 11, 2, 12, 5],
		senses: "Blindsight 10 ft",
		passivePerception: 11,
		challengeRating: "1/8",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Flyby",
			description: "The [THIS] doesn't provoke an Opportunity Attack when it flies out of an enemy's reach.",
		}],
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, "", "piercing"],
			range: "Melee (5 ft)",
			description: "+1d4 Poison damage",
			abilitytodamage: false,
		}],
	},
	"giant eagle": {
		name: "Giant Eagle",
		nameAlt: ["Eagle, Giant"],
		source: [["SRD24", 350], ["M24", 356]],
		size: 2,
		type: "Celestial",
		alignment: "Neutral Good",
		ac: 13,
		hp: 26,
		hd: [4, 10],
		speed: "10 ft, fly 80 ft",
		scores: [16, 17, 13, 8, 14, 10],
		skills: {
			"perception": 6,
		},
		resistances: "Necrotic, Radiant",
		passivePerception: 16,
		languages: "Celestial; understands Common and Primordial (Auran) but can't speak them",
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 2,
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Rend attacks.",
		}],
		attacks: [{
			name: "Rend",
			ability: 1,
			damage: [1, 4, "slashing"],
			range: "Melee (5 ft)",
			description: "+1d6 Radiant damage; Two Rend attacks as an Action",
		}],
	},
	"giant elk": {
		name: "Giant Elk",
		nameAlt: ["Elk, Giant"],
		source: [["SRD24", 351], ["M24", 356]],
		size: 1,
		type: "Celestial",
		alignment: "Neutral Good",
		ac: 14,
		hp: 42,
		hd: [5, 12],
		speed: "60 ft",
		scores: [19, 18, 14, 7, 14, 10],
		saves: [6, 6, "", "", "", ""],
		skills: {
			"perception": 4,
		},
		resistances: "Necrotic, Radiant",
		senses: "Darkvision 90 ft",
		passivePerception: 14,
		languages: "Celestial; understands Common, Elvish, and Sylvan but can't speak them",
		challengeRating: "2",
		proficiencyBonus: 2,
		attacksAction: 1,
		addMod: [{
			type: "skill", field: "Init", mod: "Prof",
			text: "The elk adds its Proficiency Bonus to its Initiative rolls.",
		}],
		actions: [{
			name: "Ram",
			description: "If the target is a Huge or smaller creature and the [THIS] moved at least 20 ft straight toward it immediately before the hit, the target takes an extra 2d4 Bludgeoning damage and has the Prone condition.",
		}],
		attacks: [{
			name: "Ram",
			ability: 1,
			damage: [2, 6, "bludgeoning"],
			range: "Melee (10 ft)",
			description: "+2d4 Radiant damage; If moved 20 ft and hit \u2264Huge: +2d4 damage \x26 knocked Prone",
		}],
	},
	"giant owl": {
		name: "Giant Owl",
		nameAlt: ["Owl, Giant"],
		source: [["SRD24", 352], ["M24", 358]],
		size: 2,
		type: "Celestial",
		alignment: "Neutral",
		ac: 12,
		hp: 19,
		hd: [3, 10],
		speed: "5 ft, fly 60 ft",
		scores: [13, 15, 12, 10, 14, 10],
		saves: ["", "", "", "", 4, ""],
		skills: {
			"perception": 6,
			"stealth": 6,
		},
		resistances: "Necrotic, Radiant",
		senses: "Darkvision 120 ft",
		passivePerception: 16,
		languages: "Celestial; understands Common, Elvish, and Sylvan but can't speak them",
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Flyby",
			description: "The [THIS] doesn't provoke an Opportunity Attack when it flies out of an enemy's reach.",
		}, {
			name: "Spellcasting",
			description: [
				"The [THIS]] can cast the following spells, requiring no spell components and using Wisdom as the spellcasting ability:",
				"**At Will**: Detect Evil and Good, Detect Magic",
				"**1/Day**: Clairvoyance",
			].join("\n"),
		}],
		attacks: [{
			name: "Talons",
			ability: 2,
			damage: [1, 10, "slashing"],
			range: "Melee (5 ft)",
		}],
	},
	"giant vulture": {
		name: "Giant Vulture",
		nameAlt: ["Vulture, Giant"],
		source: [["SRD24", 354], ["M24", 361]],
		size: 2,
		type: "Monstrosity",
		alignment: "Neutral Evil",
		ac: 10,
		hp: 25,
		hd: [3, 10],
		speed: "10 ft, fly 60 ft",
		scores: [15, 10, 16, 6, 12, 7],
		skills: {
			"perception": 3,
		},
		resistances: "Necrotic",
		senses: "Darkvision 60 ft",
		passivePerception: 13,
		languages: "Understands Common but can't speak",
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Pack Tactics",
			description: "The [THIS] has Advantage on an attack roll against a creature if at least one of the [THIS]'s allies is within 5 ft of the creature and the ally doesn't have the Incapacitated condition.",
		}],
		attacks: [{
			name: "Gouge",
			ability: 1,
			damage: [2, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "Target is Poisoned until its next turn ends",
		}],
	},
	// Beasts (Familiar & Wild Shape)
	"allosaurus": {
		name: "Allosaurus",
		source: [["SRD24", 344], ["M24", 348]],
		size: 2,
		type: "Beast",
		subtype: "Dinosaur",
		alignment: "Unaligned",
		ac: 13,
		hp: 51,
		hd: [6, 10],
		speed: "60 ft",
		scores: [19, 13, 17, 2, 12, 5],
		skills: {
			"perception": 5,
		},
		passivePerception: 15,
		challengeRating: "2",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Claws",
			description: "If the target is a Large or smaller creature and the [THIS] moved at least 30 ft straight toward it immediately before the hit, the target has the Prone condition, and the allosaurus can make one Bite attack against it.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [2, 10, "piercing"],
			range: "Melee (5 ft)",
		}, {
			name: "Claws",
			ability: 1,
			damage: [1, 8, "slashing"],
			range: "Melee (5 ft)",
			description: "If moved 30 ft and hit \u2264Large: knocked Prone \x26 extra Bite attack",
		}],
	},
	"ankylosaurus": {
		name: "Ankylosaurus",
		source: [["SRD24", 344], ["M24", 348]],
		size: 1,
		type: "Beast",
		subtype: "Dinosaur",
		alignment: "Unaligned",
		ac: 15,
		hp: 68,
		hd: [8, 12],
		speed: "30 ft",
		scores: [19, 11, 15, 2, 12, 5],
		saves: [6, "", "", "", "", ""],
		passivePerception: 11,
		challengeRating: "3",
		proficiencyBonus: 2,
		attacksAction: 2,
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Tail attacks.",
		}],
		attacks: [{
			name: "Tail",
			ability: 1,
			damage: [1, 10, "bludgeoning"],
			range: "Melee (10 ft)",
			description: "Huge or smaller creature knocked Prone",
		}],
	},
	"ape": {
		name: "Ape",
		source: [["SRD24", 344], ["M24", 348]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 19,
		hd: [3, 8],
		speed: "30 ft, climb 30 ft",
		scores: [16, 14, 14, 6, 12, 7],
		skills: {
			"athletics": 5,
			"perception": 3,
		},
		passivePerception: 13,
		challengeRating: "1/2",
		proficiencyBonus: 2,
		attacksAction: 2,
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Fist attacks.",
		}],
		attacks: [{
			name: "Fist",
			ability: 1,
			damage: [1, 4, "bludgeoning"],
			range: "Melee (5 ft)",
			description: "Two Fist attacks as an Action",
		}, {
			name: "Rock (Recharge 6)",
			ability: 1,
			damage: [2, 6, "bludgeoning"],
			range: "25/50 ft",
		}],
	},
	"archelon": {
		name: "Archelon",
		source: [["SRD24", 344], ["M24", 349]],
		size: 1,
		type: "Beast",
		subtype: "Dinosaur",
		alignment: "Unaligned",
		ac: 17,
		hp: 90,
		hd: [12, 12],
		speed: "20 ft, swim 80 ft",
		scores: [18, 16, 13, 4, 14, 6],
		skills: {
			"stealth": 5,
		},
		passivePerception: 12,
		challengeRating: "4",
		proficiencyBonus: 2,
		attacksAction: 2,
		traits: [{
			name: "Amphibious",
			description: "The [THIS] can breathe air and water.",
		}],
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Bite attacks.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [3, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "Two Bite attacks as an Action",
		}],
	},
	"baboon": {
		name: "Baboon",
		source: [["SRD24", 345], ["M24", 349]],
		size: 4,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 3,
		hd: [1, 6],
		speed: "30 ft, climb 30 ft",
		scores: [8, 14, 11, 4, 12, 6],
		passivePerception: 11,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Pack Tactics",
			description: "The [THIS] has Advantage on an attack roll against a creature if at least one of the [THIS]'s allies is within 5 ft of the creature and the ally doesn't have the Incapacitated condition.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 4, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"badger": {
		name: "Badger",
		source: [["SRD24", 345], ["M24", 349]],
		size: 5,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 5,
		hd: [1, 4],
		speed: "20 ft, burrow 5 ft",
		scores: [10, 11, 16, 2, 12, 5],
		skills: {
			"perception": 3,
		},
		resistances: "Poison",
		senses: "Darkvision 30 ft",
		passivePerception: 13,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, "", "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"bat": {
		name: "Bat",
		source: [["SRD24", 345], ["M24", 349]],
		size: 5,
		type: "Beast",
		companion: ["familiar"],
		alignment: "Unaligned",
		ac: 12,
		hp: 1,
		hd: [1, 4],
		speed: "5 ft, fly 30 ft",
		scores: [2, 15, 8, 2, 12, 4],
		senses: "Blindsight 60 ft",
		passivePerception: 11,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, "", "piercing"],
			range: "Melee (5 ft)",
			abilitytodamage: false,
		}],
	},
	"black bear": {
		name: "Black Bear",
		nameAlt: ["Bear, Black"],
		nameThis: "bear",
		source: [["SRD24", 345], ["M24", 349]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 19,
		hd: [3, 8],
		speed: "30 ft, climb 30 ft, swim 30 ft",
		scores: [15, 12, 14, 2, 12, 7],
		skills: {
			"perception": 5,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 15,
		challengeRating: "1/2",
		proficiencyBonus: 2,
		attacksAction: 2,
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Rend attacks.",
		}],
		attacks: [{
			name: "Rend",
			ability: 1,
			damage: [1, 6, "slashing"],
			range: "Melee (5 ft)",
			description: "Two Rend attacks as an Action",
		}],
	},
	"blood hawk": {
		name: "Blood Hawk",
		nameThis: "hawk",
		source: [["SRD24", 345], ["M24", 350]],
		size: 4,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 7,
		hd: [2, 6],
		speed: "10 ft, fly 60 ft",
		scores: [6, 14, 10, 3, 14, 5],
		skills: {
			"perception": 6,
		},
		passivePerception: 16,
		challengeRating: "1/8",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Pack Tactics",
			description: "The [THIS] has Advantage on an attack roll against a creature if at least one of the [THIS]'s allies is within 5 ft of the creature and the ally doesn't have the Incapacitated condition.",
		}],
		attacks: [{
			name: "Beak",
			ability: 2,
			damage: [1, 4, "piercing"],
			range: "Melee (5 ft)",
			description: "If the target is Bloodied: 1d8 damage instead",
		}],
	},
	"boar": {
		name: "Boar",
		source: [["SRD24", 346], ["M24", 350]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 13,
		hd: [2, 8],
		speed: "40 ft",
		scores: [13, 11, 14, 2, 9, 5],
		passivePerception: 9,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Bloodied Fury",
			description: "While Bloodied, the [THIS] has Advantage on attack rolls.",
		}],
		actions: [{
			name: "Gore",
			description: "If the target is a Medium or smaller creature and the [THIS] moved at least 20 ft straight toward it immediately before the hit, the target takes an extra 1d6 Piercing damage and has the Prone condition.",
		}],
		attacks: [{
			name: "Gore",
			ability: 1,
			damage: [1, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "If moved 20 ft and hit \u2264Medium: +1d6 damage \x26 knocked Prone",
		}],
	},
	"brown bear": {
		name: "Brown Bear",
		nameAlt: ["Bear, Brown"],
		nameThis: "bear",
		source: [["SRD24", 346], ["M24", 350]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 22,
		hd: [3, 10],
		speed: "40 ft, climb 30 ft",
		scores: [17, 12, 15, 2, 13, 7],
		skills: {
			"perception": 3,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 13,
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 2,
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make one Bite attack and one Claw attack.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 8, "piercing"],
			range: "Melee (5 ft)",
		}, {
			name: "Claw",
			ability: 1,
			damage: [1, 4, "slashing"],
			range: "Melee (5 ft)",
			description: "Large or smaller creature is knocked Prone",
		}],
	},
	"camel": {
		name: "Camel",
		source: [["SRD24", 346], ["M24", 351]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 10,
		hp: 17,
		hd: [2, 10],
		speed: "50 ft",
		scores: [15, 8, 17, 2, 11, 5],
		saves: ["", "", 5, "", "", ""],
		senses: "Darkvision 60 ft",
		passivePerception: 10,
		challengeRating: "1/8",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 4, "bludgeoning"],
			range: "Melee (5 ft)",
		}],
	},
	"cat": {
		name: "Cat",
		source: [["SRD24", 346], ["M24", 351]],
		size: 5,
		type: "Beast",
		companion: ["familiar"],
		alignment: "Unaligned",
		ac: 12,
		hp: 2,
		hd: [1, 4],
		speed: "40 ft, climb 40 ft",
		scores: [3, 15, 10, 3, 12, 7],
		saves: ["", 4, "", "", "", ""],
		skills: {
			"perception": 3,
			"stealth": 4,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 13,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Jumper",
			description: "The [THIS]'s jump distance is determined using its Dexterity rather than its Strength.",
		}],
		attacks: [{
			name: "Scratch",
			ability: 2,
			damage: [1, "", "slashing"],
			range: "Melee (5 ft)",
			abilitytodamage: false,
		}],
	},
	"constrictor snake": {
		name: "Constrictor Snake",
		nameAlt: ["Snake, Constrictor"],
		nameThis: "snake",
		source: [["SRD24", 346], ["M24", 351]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 13,
		hd: [2, 10],
		speed: "30 ft, swim 30 ft",
		scores: [15, 14, 12, 1, 10, 3],
		skills: {
			"perception": 2,
			"stealth": 4,
		},
		senses: "Blindsight 10 ft",
		passivePerception: 12,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Constrict",
			description: "One Medium or smaller creature the [THIS] can see within 5 ft must make a DC 12 Strength saving throw or take 3d4 Bludgeoning damage and have the Grappled condition (escape DC 12).",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 8, "piercing"],
			range: "Melee (5 ft)",
		}, {
			name: "Constrict",
			ability: 1,
			damage: [3, 4, "bludgeoning"],
			range: "5 ft (\u2264Medium)",
			description: "Str save to avoid; Only \u2264Medium creatures; Also Grappled (escape DC 12)",
			dc: true,
			abilitytodamage: false,
		}],
	},
	"crab": {
		name: "Crab",
		source: [["SRD24", 347], ["M24", 351]],
		size: 5,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 3,
		hd: [1, 4],
		speed: "20 ft, swim 20 ft",
		scores: [6, 11, 12, 1, 8, 2],
		skills: {
			"stealth": 2,
		},
		senses: "Blindsight 30 ft",
		passivePerception: 9,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Amphibious",
			description: "The [THIS] can breathe air and water.",
		}],
		attacks: [{
			name: "Claw",
			ability: 2,
			damage: [1, "", "bludgeoning"],
			range: "Melee (5 ft)",
		}],
	},
	"crocodile": {
		name: "Crocodile",
		source: [["SRD24", 347], ["M24", 352]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 13,
		hd: [2, 10],
		speed: "20 ft, swim 30 ft",
		scores: [15, 10, 13, 2, 10, 5],
		saves: ["", "", 3, "", "", ""],
		skills: {
			"stealth": 2,
		},
		passivePerception: 10,
		challengeRating: "1/2",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Hold Breath",
			description: "The [THIS] can hold its breath for 1 hour.",
		}],
		actions: [{
			name: "Bite",
			description: "If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 12). While Grappled, the target has the Restrained condition.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 8, "piercing"],
			range: "Melee (5 ft)",
			description: "\u2264Medium is Grappled (escape DC 12); Restrained while Grappled",
		}],
	},
	"deer": {
		name: "Deer",
		source: [["SRD24", 347], ["M24", 352]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 4,
		hd: [1, 8],
		speed: "50 ft",
		scores: [11, 16, 11, 2, 14, 5],
		skills: {
			"perception": 4,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 14,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Agile",
			description: "The [THIS] doesn't provoke an Opportunity Attack when it moves out of an enemy's reach.",
		}],
		attacks: [{
			name: "Ram",
			ability: 1,
			damage: [1, 4, "bludgeoning"],
			range: "Melee (5 ft)",
		}],
	},
	"dire wolf": {
		name: "Dire Wolf",
		nameAlt: ["Wolf, Dire"],
		nameThis: "wolf",
		source: [["SRD24", 347], ["M24", 352]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 14,
		hp: 22,
		hd: [3, 10],
		speed: "50 ft",
		scores: [17, 15, 15, 3, 12, 7],
		skills: {
			"perception": 5,
			"stealth": 4,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 15,
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Pack Tactics",
			description: "The [THIS] has Advantage on an attack roll against a creature if at least one of the [THIS]'s allies is within 5 ft of the creature and the ally doesn't have the Incapacitated condition.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 10, "piercing"],
			range: "Melee (5 ft)",
			description: "Large or smaller creature is knocked Prone",
		}],
	},
	"draft horse": {
		name: "Draft Horse",
		nameAlt: ["Horse, Draft"],
		nameThis: "horse",
		source: [["SRD24", 347], ["M24", 352]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 10,
		hp: 15,
		hd: [2, 10],
		speed: "40 ft",
		scores: [18, 10, 15, 2, 11, 7],
		passivePerception: 10,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Hooves",
			ability: 1,
			damage: [1, 4, "bludgeoning"],
			range: "Melee (5 ft)",
		}],
	},
	"eagle": {
		name: "Eagle",
		source: [["SRD24", 348], ["M24", 353]],
		size: 4,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 4,
		hd: [1, 6],
		speed: "10 ft, fly 60 ft",
		scores: [6, 15, 12, 2, 14, 7],
		skills: {
			"perception": 6,
		},
		passivePerception: 16,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Talons",
			ability: 2,
			damage: [1, 4, "slashing"],
			range: "Melee (5 ft)",
		}],
	},
	"elephant": {
		name: "Elephant",
		source: [["SRD24", 348], ["M24", 353]],
		size: 1,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 76,
		hd: [8, 12],
		speed: "40 ft",
		scores: [22, 9, 17, 3, 11, 6],
		passivePerception: 10,
		challengeRating: "4",
		proficiencyBonus: 2,
		attacksAction: 2,
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Gore attacks.",
		}, {
			name: "Gore",
			description: "If the target is a Huge or smaller creature and the [THIS] moved at least 20 ft straight toward it immediately before the hit, the target has the Prone condition.",
		}],
		attacks: [{
			name: "Gore",
			ability: 1,
			damage: [2, 8, "piercing"],
			range: "Melee (5 ft)",
			description: "If moved 20 ft and hit \u2264Huge: knocked Prone; Two Gore attacks as an Action",
		}, {
			name: "Trample",
			ability: 1,
			damage: [2, 10, "Bludgeoning"],
			range: "Melee (5 ft)",
			dc: true,
			description: "As a Bonus Action vs. Prone creature; Dex save to halve damage",
		}],
	},
	"elk": {
		name: "Elk",
		nameAlt: ["Reindeer", "Yak"], // Reindeer from Icewind Dale: Rime of the Frostmaiden, Yak from Storm King's Thunder
		source: [["SRD24", 348], ["M24", 353]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 10,
		hp: 11,
		hd: [2, 10],
		speed: "50 ft",
		scores: [16, 10, 11, 2, 10, 6],
		skills: {
			"perception": 2,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 12,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Ram",
			description: "If the target is a Large or smaller creature and the [THIS] moved at least 20 ft straight toward it immediately before the hit, the target takes an extra 1d6 Bludgeoning damage and has the Prone condition.",
		}],
		attacks: [{
			name: "Ram",
			ability: 1,
			damage: [1, 6, "bludgeoning"],
			range: "Melee (5 ft)",
			description: "If moved 20 ft and hit \u2264Large: +1d6 damage \x26 knocked Prone",
		}],
	},
	"frog": {
		name: "Frog",
		nameAlt: ["Toad"],
		source: [["SRD24", 348], ["M24", 354]],
		size: 5,
		type: "Beast",
		companion: ["familiar"],
		alignment: "Unaligned",
		ac: 11,
		hp: 1,
		hd: [1, 4],
		speed: "20 ft, swim 20 ft",
		scores: [1, 13, 8, 1, 8, 3],
		skills: {
			"perception": 1,
			"stealth": 3,
		},
		senses: "Darkvision 30 ft",
		passivePerception: 11,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Amphibious",
			description: "The [THIS] can breathe air and water.",
		}, {
			name: "Standing Leap",
			description: "The [THIS]'s Long Jump is up to 10 ft and its High Jump is up to 5 ft with or without a running start.",
		}],
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, "", "piercing"],
			range: "Melee (5 ft)",
			abilitytodamage: false,
		}],
	},
	"giant ape": {
		name: "Giant Ape",
		nameAlt: ["Ape, Giant"],
		source: [["SRD24", 349], ["M24", 354]],
		size: 1,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 168,
		hd: [16, 12],
		speed: "40 ft, climb 40 ft",
		scores: [23, 14, 18, 5, 12, 7],
		skills: {
			"athletics": 9,
			"perception": 4,
			"survival": 4,
		},
		passivePerception: 14,
		challengeRating: "7",
		proficiencyBonus: 3,
		attacksAction: 2,
		addMod: [{
			type: "skill", field: "Init", mod: "Prof",
			text: "The ape adds its Proficiency Bonus to its Initiative rolls.",
		}],
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Fist attacks.",
		}, {
			name: "Boulder Toss (Recharge 6)",
			description: "The [THIS] hurls a boulder at a point it can see within 90 ft. Dex save DC 17, each creature in a 5-ft-radius Sphere centered on that point. *Failure:* 7d6 Bludgeoning damage. If the target is a Large or smaller creature, it has the Prone condition. *Success:* Half damage only.",
		}, {
			name: "Leap",
			description: "As a Bonus Action, the [THIS] jumps up to 30 ft by spending 10 ft of movement.",
		}],
		attacks: [{
			name: "Fist",
			ability: 1,
			damage: [3, 10, "bludgeoning"],
			range: "Melee (10 ft)",
			description: "Two Fist attacks as an Action",
		}, {
			name: "Boulder Toss (Recharge 6)",
			ability: 1,
			damage: [7, 6, "bludgeoning"],
			range: "90 ft",
			description: "All in 5-ft rad Sphere; \u2264Large knocked Prone; Dex save for half damage only",
			dc: true,
			abilitytodamage: false,
		}],
	},
	"giant badger": {
		name: "Giant Badger",
		nameAlt: ["Badger, Giant"],
		source: [["SRD24", 349], ["M24", 354]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 15,
		hd: [2, 8],
		speed: "30 ft, burrow 10 ft",
		scores: [13, 10, 17, 2, 12, 5],
		skills: {
			"perception": 3,
		},
		resistances: "Poison",
		senses: "Darkvision 60 ft",
		passivePerception: 13,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [2, 4, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"giant bat": {
		name: "Giant Bat",
		nameAlt: ["Bat, Giant"],
		source: [["SRD24", 349], ["M24", 355]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 22,
		hd: [4, 10],
		speed: "10 ft, fly 60 ft",
		scores: [15, 16, 11, 2, 12, 6],
		senses: "Blindsight 120 ft",
		passivePerception: 11,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, 6, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"giant boar": {
		name: "Giant Boar",
		nameAlt: ["Boar, Giant"],
		source: [["SRD24", 349], ["M24", 355]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 42,
		hd: [5, 10],
		speed: "40 ft",
		scores: [17, 10, 16, 2, 7, 5],
		saves: [5, "", "", "", "", ""],
		passivePerception: 8,
		challengeRating: "2",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Bloodied Fury",
			description: "The [THIS] has Advantage on melee attack rolls while it is Bloodied.",
		}],
		actions: [{
			name: "Gore",
			description: "If the target is a Large or smaller creature and the [THIS] moved at least 20 ft straight toward it immediately before the hit, the target takes an extra 2d6 Piercing damage and has the Prone condition.",
		}],
		attacks: [{
			name: "Gore",
			ability: 1,
			damage: [2, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "If moved 20 ft and hit \u2264Large: +2d6 damage \x26 knocked Prone",
		}],
	},
	"giant centipede": {
		name: "Giant Centipede",
		nameAlt: ["Centipede, Giant"],
		source: [["SRD24", 349], ["M24", 355]],
		size: 4,
		type: "Beast",
		alignment: "Unaligned",
		ac: 14,
		hp: 9,
		hd: [2, 6],
		speed: "30 ft, climb 30 ft",
		scores: [5, 14, 12, 1, 7, 3],
		senses: "Blindsight 30 ft",
		passivePerception: 8,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, 4, "piercing"],
			range: "Melee (5 ft)",
			description: "Target is Poisoned until the centipede's next turn starts",
		}],
	},
	"giant constrictor snake": {
		name: "Giant Constrictor Snake",
		nameAlt: ["Snake, Giant Constrictor"],
		nameThis: "snake",
		source: [["SRD24", 350], ["M24", 355]],
		size: 1,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 60,
		hd: [8, 12],
		speed: "30 ft, swim 30 ft",
		scores: [19, 14, 12, 1, 10, 3],
		skills: {
			"perception": 2,
		},
		senses: "Blindsight 10 ft",
		passivePerception: 12,
		challengeRating: "2",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make one Bite attack and use Constrict.",
		}, {
			name: "Constrict",
			description: "One Large or smaller creature the [THIS] can see within 10 ft must make a DC 12 Strength saving throw or take 2d8+4 Bludgeoning damage and have the Grappled condition (escape DC 12).",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [2, 6, "piercing"],
			range: "Melee (10 ft)",
		}, {
			name: "Constrict",
			ability: 1,
			damage: [2, 8, "bludgeoning"],
			range: "10 ft (\u2264Large)",
			description: "Str save to avoid; Only \u2264Large creatures; Also Grappled (escape same DC)",
			dc: true,
		}],
	},
	"giant crab": {
		name: "Giant Crab",
		nameAlt: ["Crab, Giant"],
		source: [["SRD24", 350], ["M24", 356]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 15,
		hp: 13,
		hd: [3, 8],
		speed: "30 ft, swim 30 ft",
		scores: [13, 13, 11, 1, 9, 3],
		skills: {
			"stealth": 3,
		},
		senses: "Blindsight 30 ft",
		passivePerception: 9,
		challengeRating: "1/8",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Amphibious",
			description: "The [THIS] can breathe air and water.",
		}, {
			name: "Claw",
			description: "If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 11) from one of two claws.",
		}],
		attacks: [{
			name: "Claw",
			ability: 1,
			damage: [1, 6, "bludgeoning"],
			range: "Melee (5 ft)",
			description: "\u2264Medium is Grappled (escape DC 11)",
		}],
	},
	"giant crocodile": {
		name: "Giant Crocodile",
		nameAlt: ["Crocodile, Giant", "Whirlwyrm"], // Whirlwyrm from Turn of Fortune's Wheel (Planescape)
		source: [["SRD24", 350], ["M24", 356]],
		size: 1,
		type: "Beast",
		alignment: "Unaligned",
		ac: 14,
		hp: 85,
		hd: [9, 12],
		speed: "30 ft, swim 50 ft",
		scores: [21, 9, 17, 2, 10, 7],
		skills: {
			"stealth": 5,
		},
		passivePerception: 10,
		challengeRating: "5",
		proficiencyBonus: 3,
		attacksAction: 2,
		traits: [{
			name: "Hold Breath",
			description: "The [THIS] can hold its breath for 1 hour.",
		}],
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make one Bite attack and one Tail attack.",
		}, {
			name: "Bite",
			description: "If the target is a Large or smaller creature, it has the Grappled condition (escape DC 15; i.e. Bite To Hit + 8). While Grappled, the target has the Restrained condition and can't be targeted by the [THIS]'s Tail.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [3, 10, "piercing"],
			range: "Melee (5 ft)",
			description: "\u2264Large is Grappled (escape DC 15); Restrained while Grappled",
		}, {
			name: "Tail",
			ability: 1,
			damage: [3, 8, "bludgeoning"],
			range: "Melee (10 ft)",
			description: "Large or smaller creature is knocked Prone",
		}],
	},
	"giant fire beetle": {
		name: "Giant Fire Beetle",
		nameAlt: ["Beetle, Giant Fire"],
		nameThis: "beetle",
		source: [["SRD24", 351], ["M24", 357]],
		size: 4,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 4,
		hd: [1, 6],
		speed: "30 ft, climb 30 ft",
		scores: [8, 10, 12, 1, 7, 3],
		resistances: "Fire",
		senses: "Blindsight 30 ft",
		passivePerception: 8,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Illumination",
			description: "The [THIS] sheds Bright Light in a 10-ft radius and Dim Light for an additional 10 ft.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, "", "fire"],
			range: "Melee (5 ft)",
			abilitytodamage: false,
		}],
	},
	"giant fly": {
		name: "Giant Fly",
		nameAlt: ["Fly, Giant"],
		source: [["SRD24", 222], ["DMG24", 261]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 19,
		hd: [3, 10],
		speed: "30 ft, fly 60 ft",
		scores: [14, 13, 13, 2, 10, 3],
		senses: "Darkvision 60 ft",
		passivePerception: 10,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 0,
		attacks: [],
	},
	"giant frog": {
		name: "Giant Frog",
		nameAlt: ["Frog, Giant"],
		source: [["SRD24", 351], ["M24", 357]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 18,
		hd: [4, 8],
		speed: "30 ft, swim 30 ft",
		scores: [12, 13, 11, 2, 10, 3],
		skills: {
			"perception": 2,
			"stealth": 4,
		},
		senses: "Darkvision 30 ft",
		passivePerception: 12,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		features: [{
			name: "Amphibious",
			description: "The [THIS] can breathe air and water.",
		}, {
			name: "Standing Leap",
			description: "The [THIS]'s Long Jump is up to 20 ft and its High Jump is up to 10 ft with or without a running start.",
		}],
		actions: [{
			name: "Swallow",
			description: "As an Action, the [THIS] swallows a Small or smaller target it is grappling. While swallowed, the target isn't Grappled but has the Blinded and Restrained conditions, and it has Total Cover against attacks and other effects outside the [THIS]. While swallowing the target, the [THIS] can't use Bite, and if it dies, the swallowed target is no longer Restrained and can escape from the corpse using 5 ft of movement, exiting with the Prone condition.\nAt the end of the [THIS]'s next turn, the swallowed target takes 2d4 Acid damage. If that damage doesn't kill it, the [THIS] disgorges it, causing it to exit Prone.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 11).",
			modifiers: ["", 1],
		}],
	},
	"giant goat": {
		name: "Giant Goat",
		nameAlt: ["Goat, Giant", "Moose"], // Moose from Icewind Dale: Rime of the Frostmaiden
		source: [["SRD24", 351], ["M24", 357]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 19,
		hd: [3, 10],
		speed: "40 ft, climb 30 ft",
		scores: [17, 13, 12, 3, 12, 6],
		saves: [5, "", "", "", "", ""],
		skills: {
			"perception": 3,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 13,
		challengeRating: "1/2",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Ram",
			description: "If the target is a Large or smaller creature and the [THIS] moved at least 20 ft straight toward it immediately before the hit, the target takes an extra 2d4 Bludgeoning damage and has the Prone condition.",
		}],
		attacks: [{
			name: "Ram",
			ability: 1,
			damage: [1, 6, "bludgeoning"],
			range: "Melee (5 ft)",
			description: "If moved 20 ft and hit \u2264Large: +2d4 damage \x26 knocked Prone",
		}],
	},
	"giant hyena": {
		name: "Giant Hyena",
		nameAlt: ["Hyena, Giant"],
		source: [["SRD24", 352], ["M24", 357]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 45,
		hd: [6, 10],
		speed: "50 ft",
		scores: [16, 14, 14, 2, 12, 7],
		skills: {
			"perception": 3,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 13,
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Rampage (1/Day)",
			description: "As a Bonus Action, immediately after dealing damage to a creature that was already Bloodied, the [THIS] can move up to half its Speed, and it makes one Bite attack.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [2, 6, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"giant lizard": {
		name: "Giant Lizard",
		nameAlt: ["Lizard, Giant"],
		source: [["SRD24", 352], ["M24", 358]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 19,
		hd: [3, 10],
		speed: "40 ft, climb 40 ft",
		scores: [15, 12, 13, 2, 10, 5],
		saves: ["", 3, "", "", "", ""],
		senses: "Darkvision 60 ft",
		passivePerception: 10,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Spider Climb",
			description: "The [THIS] can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 8, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"giant octopus": {
		name: "Giant Octopus",
		nameAlt: ["Octopus, Giant"],
		source: [["SRD24", 352], ["M24", 358]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 45,
		hd: [7, 10],
		speed: "10 ft, swim 60 ft",
		scores: [17, 13, 13, 5, 10, 4],
		skills: {
			"perception": 4,
			"stealth": 5,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 14,
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 1,
		features: [{
			name: "Water Breathing",
			description: "The [THIS] can breathe only underwater. It can hold its breath for 1 hour outside water.",
		}],
		actions: [{
			name: "Ink Cloud (1/Day)",
			description: "As a Reaction when the [THIS] takes damage while underwater, it can release ink that fills a 10-ft Cube centered on itself, and it moves up to its Swim Speed. The Cube is Heavily Obscured for 1 minute or until a strong current or similar effect disperses the ink.",
		}, {
			name: "Tentacles",
			description: "If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 13) from all eight tentacles. While Grappled, the target has the Restrained condition.",
		}],
		attacks: [{
			name: "Tentacles",
			ability: 1,
			damage: [2, 6, "bludgeoning"],
			range: "Melee (10 ft)",
			description: "\u2264Medium is Grappled (escape DC 13); Restrained while Grappled",
		}],
	},
	"giant rat": {
		name: "Giant Rat",
		nameAlt: ["Rat, Giant"],
		source: [["SRD24", 353], ["M24", 358]],
		size: 4,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 7,
		hd: [2, 6],
		speed: "30 ft, climb 30 ft",
		scores: [7, 16, 11, 2, 10, 4],
		saves: ["", 5, "", "", "", ""],
		skills: {
			"perception": 2,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 12,
		challengeRating: "1/8",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Pack Tactics",
			description: "The [THIS] has Advantage on an attack roll against a creature if at least one of the [THIS]'s allies is within 5 ft of the creature and the ally doesn't have the Incapacitated condition.",
		}],
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, 4, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"giant scorpion": {
		name: "Giant Scorpion",
		nameAlt: ["Scorpion, Giant"],
		source: [["SRD24", 353], ["M24", 359]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 15,
		hp: 52,
		hd: [7, 10],
		speed: "40 ft",
		scores: [16, 13, 15, 1, 9, 3],
		senses: "Blindsight 60 ft",
		passivePerception: 9,
		challengeRating: "3",
		proficiencyBonus: 2,
		attacksAction: 3,
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Claw attacks and one Sting attack.",
		}, {
			name: "Claw",
			description: "If the target is a Large or smaller creature, it has the Grappled condition (escape DC 13) from one of two claws.",
		}],
		attacks: [{
			name: "Claw",
			ability: 1,
			damage: [1, 6, "bludgeoning"],
			range: "Melee (5 ft)",
			description: "\u2264Large is Grappled (escape DC 13)",
		}, {
			name: "Sting",
			ability: 1,
			damage: [1, 8, "piercing"],
			range: "Melee (5 ft)",
			description: "+2d10 Poison damage",
		}],
	},
	"giant seahorse": {
		name: "Giant Seahorse",
		source: [["SRD24", 353], ["M24", 359]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 14,
		hp: 16,
		hd: [3, 10],
		speed: "5 ft, swim 40 ft",
		scores: [15, 12, 11, 2, 12, 5],
		passivePerception: 11,
		challengeRating: "1/2",
		proficiencyBonus: 2,
		attacksAction: 1,
		features: [{
			name: "Water Breathing",
			description: "The [THIS] can breathe only underwater.",
		}],
		actions: [{
			name: "Bubble Dash",
			description: "As a Bonus Action, while underwater, the [THIS] moves up to half its Swim Speed without provoking Opportunity Attacks.",
		}, {
			name: "Ram",
			description: "If the [THIS] moved at least 20 ft straight toward the target immediately before the hit, the attack deals 2d8 damage instead of 2d6.",
		}],
		attacks: [{
			name: "Ram",
			ability: 1,
			damage: [2, 6, "bludgeoning"],
			range: "Melee (5 ft)",
			description: "If moved 20 ft before hit, 2d8 damage instead of 2d6",
		}],
	},
	"giant shark": {
		name: "Giant Shark",
		nameAlt: ["Shark, Giant"],
		source: [["SRD24", 353], ["M24", 359]],
		size: 1,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 92,
		hd: [8, 12],
		speed: "5 ft, swim 60 ft",
		scores: [23, 11, 21, 1, 10, 5],
		skills: {
			"perception": 3,
		},
		senses: "Blindsight 60 ft",
		passivePerception: 13,
		challengeRating: "5",
		proficiencyBonus: 3,
		attacksAction: 2,
		addMod: [{
			type: "skill", field: "Init", mod: "Prof",
			text: "The shark adds its Proficiency Bonus to its Initiative rolls.",
		}],
		features: [{
			name: "Water Breathing",
			description: "The [THIS] can breathe only underwater.",
		}],
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Bite attacks.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [3, 10, "piercing"],
			range: "Melee (5 ft)",
			description: "Adv. if target is not at full HP; Two Bite attacks as an Action",
		}],
	},
	"giant spider": {
		name: "Giant Spider",
		nameAlt: ["Spider, Giant"],
		source: [["SRD24", 353], ["M24", 359]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 14,
		hp: 26,
		hd: [4, 10],
		speed: "30 ft, climb 30 ft",
		scores: [14, 16, 12, 2, 11, 4],
		skills: {
			"perception": 4,
			"stealth": 7,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 14,
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Spider Climb",
			description: "The [THIS] can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
		}, {
			name: "Web Walker",
			description: "The [THIS] ignores movement restrictions caused by webs, and it knows the location of any other creature in contact with the same web.",
		}, {
			name: "Web (Recharge 5-6)",
			description: "Dex save, one creature the [THIS] can see within 60 ft. *Failure:* The target has the Restrained condition until the web is destroyed (AC 10; HP 5; Vulnerability to Fire damage; Immunity to Poison and Psychic damage).",
		}],
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, 8, "piercing"],
			range: "Melee (5 ft)",
			description: "+2d6 Poison damage",
		}, {
			name: "Web (Recharge 5-6)",
			ability: 2,
			damage: ["Dex save", "", "Restrained"],
			range: "60 ft",
			description: "Save avoids; Lasts until web is destroyed",
			dc: true,
			abilitytodamage: false,
		}],
	},
	"giant toad": {
		name: "Giant Toad",
		nameAlt: ["Toad, Giant"],
		source: [["SRD24", 354], ["M24", 360]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 39,
		hd: [6, 10],
		speed: "30 ft, swim 30 ft",
		scores: [15, 13, 13, 2, 10, 3],
		senses: "Darkvision 60 ft",
		passivePerception: 10,
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 1,
		features: [{
			name: "Amphibious",
			description: "The [THIS] can breathe air and water.",
		}, {
			name: "Standing Leap",
			description: "The [THIS]'s Long Jump is up to 20 ft and its High Jump is up to 10 ft with or without a running start.",
		}],
		actions: [{
			name: "Swallow",
			description: "As an Action, the [THIS] swallows a Medium or smaller target it is grappling. While swallowed, the target isn't Grappled but has the Blinded and Restrained conditions, and it has Total Cover against attacks and other effects outside the [THIS]. In addition, the target takes 3d6 Acid damage at the end of each of the [THIS]'s turns. The [THIS] can have only one target swallowed at a time, and it can't use Bite while it has a swallowed target. If the [THIS] dies, a swallowed creature is no longer Restrained and can escape from the corpse using 5 ft of movement, exiting with the Prone condition.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "+2d4 Poison damage If the target is a Medium or smaller creature, it has the Grappled condition (escape DC 12).",
		}],
	},
	"giant venomous snake": {
		name: "Giant Venomous Snake",
		nameAlt: ["Snake, Giant Venomous"],
		nameThis: "snake",
		source: [["SRD24", 354], ["M24", 361]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 14,
		hp: 11,
		hd: [2, 8],
		speed: "40 ft, swim 40 ft",
		scores: [10, 18, 13, 2, 10, 3],
		skills: {
			"perception": 2,
		},
		senses: "Blindsight 10 ft",
		passivePerception: 12,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, 4, "piercing"],
			range: "Melee (10 ft)",
			description: "+1d8 Poison damage",
		}],
	},
	"giant wasp": {
		name: "Giant Wasp",
		nameAlt: ["Wasp, Giant"],
		source: [["SRD24", 354], ["M24", 361]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 22,
		hd: [5, 8],
		speed: "10 ft, fly 50 ft",
		scores: [10, 14, 10, 1, 10, 3],
		passivePerception: 10,
		challengeRating: "1/2",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Flyby",
			description: "The [THIS] doesn't provoke an Opportunity Attack when it flies out of an enemy's reach.",
		}],
		attacks: [{
			name: "Sting",
			ability: 2,
			damage: [1, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "+2d4 Poison damage",
		}],
	},
	"giant weasel": {
		name: "Giant Weasel",
		nameAlt: ["Weasel, Giant"],
		source: [["SRD24", 355], ["M24", 361]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 9,
		hd: [2, 8],
		speed: "40 ft, climb 30 ft",
		scores: [11, 17, 10, 4, 12, 5],
		skills: {
			"acrobatics": 5,
			"perception": 3,
			"stealth": 5,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 13,
		challengeRating: "1/8",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, 4, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"giant wolf spider": {
		name: "Giant Wolf Spider",
		nameAlt: ["Wolf Spider, Giant"],
		nameThis: "spider",
		source: [["SRD24", 355], ["M24", 362]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 11,
		hd: [2, 8],
		speed: "40 ft, climb 40 ft",
		scores: [12, 16, 13, 3, 12, 4],
		skills: {
			"perception": 3,
			"stealth": 7,
		},
		senses: "Blindsight 10 ft, Darkvision 60 ft",
		passivePerception: 13,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Spider Climb",
			description: "The [THIS] can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
		}],
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, 4, "piercing"],
			range: "Melee (5 ft)",
			description: "+2d4 Poison damage",
		}],
	},
	"goat": {
		name: "Goat",
		source: [["SRD24", 355], ["M24", 362]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 10,
		hp: 4,
		hd: [1, 8],
		speed: "40 ft, climb 30 ft",
		scores: [11, 10, 11, 2, 10, 5],
		saves: [2, "", "", "", "", ""],
		skills: {
			"perception": 2,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 12,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Ram",
			description: "If the [THIS] moved at least 20 ft straight toward the target immediately before the hit, the attack deals 1d4 damage instead of 1.",
		}],
		attacks: [{
			name: "Ram",
			ability: 1,
			damage: [1, "", "bludgeoning"],
			range: "Melee (5 ft)",
			description: "If moved 20 ft before hit, 1d4 damage instead",
		}],
	},
	"hawk": {
		name: "Hawk",
		nameAlt: ["Falcon"], // from Waterdeep: Dragon Heist
		source: [["SRD24", 355], ["M24", 362]],
		companion: ["familiar"],
		size: 5,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 1,
		hd: [1, 4],
		speed: "10 ft, fly 60 ft",
		scores: [5, 16, 8, 2, 14, 6],
		skills: {
			"perception": 6,
		},
		passivePerception: 16,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Talons",
			ability: 2,
			damage: [1, "", "slashing"],
			range: "Melee (5 ft)",
			abilitytodamage: false,
		}],
	},
	"hippopotamus": {
		name: "Hippopotamus",
		source: [["SRD24", 355], ["M24", 362]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 14,
		hp: 82,
		hd: [11, 10],
		speed: "30 ft, swim 30 ft",
		scores: [21, 7, 15, 2, 12, 4],
		saves: [7, "", "", "", "", ""],
		skills: {
			"perception": 3,
		},
		passivePerception: 13,
		challengeRating: "4",
		proficiencyBonus: 2,
		attacksAction: 2,
		traits: [{
			name: "Hold Breath",
			description: "The [THIS] can hold its breath for 10 minutes.",
		}],
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Bite attacks.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [2, 10, "piercing"],
			range: "Melee (5 ft)",
			description: "Two Bite attacks as an Action",
		}],
	},
	"hunter shark": {
		name: "Hunter Shark",
		nameAlt: ["Shark, Hunter"],
		nameThis: "shark",
		source: [["SRD24", 356], ["M24", 363]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 45,
		hd: [6, 10],
		speed: "5 ft, swim 40 ft",
		scores: [18, 14, 15, 1, 10, 4],
		skills: {
			"perception": 2,
		},
		senses: "Blindsight 60 ft",
		passivePerception: 12,
		challengeRating: "2",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Water Breathing",
			description: "The [THIS] can breathe only underwater.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [3, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "Adv. if target is not at full HP",
		}],
	},
	"hyena": {
		name: "Hyena",
		source: [["SRD24", 356], ["M24", 363]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 5,
		hd: [1, 8],
		speed: "50 ft",
		scores: [11, 13, 12, 2, 12, 5],
		skills: {
			"perception": 3,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 13,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Pack Tactics",
			description: "The [THIS] has Advantage on an attack roll against a creature if at least one of the [THIS]'s allies is within 5 ft of the creature and the ally doesn't have the Incapacitated condition.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 6, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"jackal": {
		name: "Jackal",
		source: [["SRD24", 356], ["M24", 364]],
		size: 4,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 3,
		hd: [1, 6],
		speed: "40 ft",
		scores: [8, 15, 11, 3, 12, 6],
		skills: {
			"perception": 5,
			"stealth": 4,
		},
		senses: "Darkvision 90 ft",
		passivePerception: 15,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 4, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"killer whale": {
		name: "Killer Whale",
		nameAlt: ["Orca"],
		nameThis: "orca",
		source: [["SRD24", 356], ["M24", 364]],
		size: 1,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 90,
		hd: [12, 12],
		speed: "5 ft, swim 60 ft",
		scores: [19, 14, 13, 3, 12, 7],
		skills: {
			"perception": 3,
			"stealth": 4,
		},
		senses: "Blindsight 120 ft",
		passivePerception: 13,
		challengeRating: "3",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Hold Breath",
			description: "The [THIS] can hold its breath for 30 minutes.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [5, 6, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"lion": {
		name: "Lion",
		source: [["SRD24", 356], ["M24", 364]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 22,
		hd: [4, 10],
		speed: "50 ft",
		scores: [17, 15, 11, 3, 12, 8],
		skills: {
			"perception": 3,
			"stealth": 4,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 13,
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 3,
		traits: [{
			name: "Pack Tactics",
			description: "The [THIS] has Advantage on an attack roll against a creature if at least one of the [THIS]'s allies is within 5 ft of the creature and the ally doesn't have the Incapacitated condition.",
		}, {
			name: "Running Leap",
			description: "With a 10-ft running start, the [THIS] can Long Jump up to 25 ft.",
		}],
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Rend attacks. It can replace one attack with a use of Roar.",
		}],
		attacks: [{
			name: "Rend",
			ability: 1,
			damage: [1, 8, "slashing"],
			range: "Melee (5 ft)",
			description: "Two Rend attacks as an Action",
		}, {
			name: "Roar",
			ability: 5,
			damage: ["Wis save", "", "Frightened"],
			range: "15 ft",
			description: "Target is Frightened until the lion's next turn starts",
			dc: true,
			abilitytodamage: false,
		}],
	},
	"lizard": {
		name: "Lizard",
		source: [["SRD24", 357], ["M24", 364]],
		size: 5,
		type: "Beast",
		companion: ["familiar"],
		alignment: "Unaligned",
		ac: 10,
		hp: 2,
		hd: [1, 4],
		speed: "20 ft, climb 20 ft",
		scores: [2, 11, 10, 1, 8, 3],
		senses: "Darkvision 30 ft",
		passivePerception: 9,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Spider Climb",
			description: "The [THIS] can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
		}],
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, "", "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"mammoth": {
		name: "Mammoth",
		source: [["SRD24", 357], ["M24", 365]],
		size: 1,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 126,
		hd: [11, 12],
		speed: "50 ft",
		scores: [24, 9, 21, 3, 11, 6],
		saves: [10, "", 8, "", "", ""],
		passivePerception: 10,
		challengeRating: "6",
		proficiencyBonus: 3,
		attacksAction: 2,
		addMod: [{
			type: "skill", field: "Init", mod: "Prof",
			text: "The mammoth adds its Proficiency Bonus to its Initiative rolls.",
		}],
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Gore attacks.",
		}, {
			name: "Gore",
			description: "If the target is a Huge or smaller creature and the [THIS] moved at least 20 ft straight toward it immediately before the hit, the target has the Prone condition.",
		}],
		attacks: [{
			name: "Gore",
			ability: 1,
			damage: [2, 10, "piercing"],
			range: "Melee (10 ft)",
			description: "If moved 20 ft and hit \u2264Huge: knocked Prone; Two Gore attacks as an Action",
		}, {
			name: "Trample",
			ability: 1,
			damage: [4, 10, "Bludgeoning"],
			range: "Melee (5 ft)",
			dc: true,
			description: "As a Bonus Action vs. Prone creature; Dex save to halve damage",
		}],
	},
	"mastiff": {
		name: "Mastiff",
		source: [["SRD24", 357], ["M24", 365]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 5,
		hd: [1, 8],
		speed: "40 ft",
		scores: [13, 14, 12, 3, 12, 7],
		skills: {
			"perception": 5,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 15,
		challengeRating: "1/8",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "Medium or smaller creature is knocked Prone",
		}],
	},
	"mule": {
		name: "Mule",
		source: [["SRD24", 357], ["M24", 365]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 10,
		hp: 11,
		hd: [2, 8],
		speed: "40 ft",
		scores: [14, 10, 13, 2, 10, 5],
		saves: [4, "", "", "", "", ""],
		passivePerception: 10,
		challengeRating: "1/8",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Beast of Burden",
			description: "The [THIS] counts as one size larger for the purpose of determining its carrying capacity.",
		}],
		attacks: [{
			name: "Hooves",
			ability: 1,
			damage: [1, 4, "bludgeoning"],
			range: "Melee (5 ft)",
		}],
	},
	"octopus": {
		name: "Octopus",
		source: [["SRD24", 357], ["M24", 365]],
		size: 4,
		type: "Beast",
		companion: ["familiar"],
		alignment: "Unaligned",
		ac: 12,
		hp: 3,
		hd: [1, 6],
		speed: "5 ft, swim 30 ft",
		scores: [4, 15, 11, 3, 10, 4],
		skills: {
			"perception": 2,
			"stealth": 6,
		},
		senses: "Darkvision 30 ft",
		passivePerception: 12,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		features: [{
			name: "Compression",
			description: "The [THIS] can move through a space as narrow as 1 inch without expending extra movement to do so.",
		}, {
			name: "Water Breathing",
			description: "The [THIS] can breathe only underwater.",
		}],
		actions: [{
			name: "Ink Cloud (1/Day)",
			description: "As a Reaction when a creature ends its turn within 5 ft of the [THIS] while underwater, the [THIS] can release ink that fills a 5-ft Cube centered on itself, and it moves up to its Swim Speed. The Cube is Heavily Obscured for 1 minute or until a strong current or similar effect disperses the ink.",
		}],
		attacks: [{
			name: "Tentacles",
			ability: 2,
			damage: [1, "", "bludgeoning"],
			range: "Melee (5 ft)",
			abilitytodamage: false,
		}],
	},
	"owl": {
		name: "Owl",
		source: [["SRD24", 358], ["M24", 366]],
		size: 5,
		type: "Beast",
		companion: ["familiar"],
		alignment: "Unaligned",
		ac: 11,
		hp: 1,
		hd: [1, 4],
		speed: "5 ft, fly 60 ft",
		scores: [3, 13, 8, 2, 12, 7],
		skills: {
			"perception": 5,
			"stealth": 5,
		},
		senses: "Darkvision 120 ft",
		passivePerception: 15,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Flyby",
			description: "The [THIS] doesn't provoke Opportunity Attacks when it flies out of an enemy's reach.",
		}],
		attacks: [{
			name: "Talons",
			ability: 2,
			damage: [1, "", "slashing"],
			range: "Melee (5 ft)",
			abilitytodamage: false,
		}],
	},
	"panther": {
		name: "Panther",
		source: [["SRD24", 358], ["M24", 366]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 13,
		hd: [3, 8],
		speed: "50 ft, climb 40 ft",
		scores: [14, 16, 10, 3, 14, 7],
		skills: {
			"perception": 4,
			"stealth": 6,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 14,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Nimble Escape",
			description: "The [THIS] can take the Disengage or Hide action as a Bonus Action.",
		}],
		attacks: [{
			name: "Rend",
			ability: 2,
			damage: [1, 6, "slashing"],
			range: "Melee (5 ft)",
		}],
	},
	"piranha": {
		name: "Piranha",
		source: [["SRD24", 358], ["M24", 366]],
		size: 5,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 1,
		hd: [1, 4],
		speed: "5 ft, swim 40 ft",
		scores: [2, 16, 9, 1, 7, 2],
		senses: "Darkvision 60 ft",
		passivePerception: 8,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Water Breathing",
			description: "The [THIS] can breathe only underwater.",
		}],
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, "", "piercing"],
			range: "Melee (5 ft)",
			description: "Adv. if target is not at full HP",
			abilitytodamage: false,
		}],
	},
	"plesiosaurus": {
		name: "Plesiosaurus",
		source: [["SRD24", 358], ["M24", 366]],
		size: 2,
		type: "Beast",
		subtype: "Dinosaur",
		alignment: "Unaligned",
		ac: 13,
		hp: 68,
		hd: [8, 10],
		speed: "20 ft, swim 40 ft",
		scores: [18, 15, 16, 2, 12, 5],
		skills: {
			"perception": 3,
			"stealth": 4,
		},
		passivePerception: 13,
		challengeRating: "2",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Hold Breath",
			description: "The [THIS] can hold its breath for 1 hour.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [2, 6, "piercing"],
			range: "Melee (10 ft)",
		}],
	},
	"polar bear": {
		name: "Polar Bear",
		nameAlt: ["Bear, Polar"],
		nameThis: "bear",
		source: [["SRD24", 359], ["M24", 367]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 42,
		hd: [5, 10],
		speed: "40 ft, swim 40 ft",
		scores: [20, 14, 16, 2, 13, 7],
		skills: {
			"perception": 5,
			"stealth": 4,
		},
		resistances: "Cold",
		senses: "Darkvision 60 ft",
		passivePerception: 15,
		challengeRating: "2",
		proficiencyBonus: 2,
		attacksAction: 2,
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Rend attacks.",
		}],
		attacks: [{
			name: "Rend",
			ability: 1,
			damage: [1, 8, "slashing"],
			range: "Melee (5 ft)",
			description: "Two Rend attacks as an Action",
		}],
	},
	"pony": {
		name: "Pony",
		source: [["SRD24", 359], ["M24", 367]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 10,
		hp: 11,
		hd: [2, 8],
		speed: "40 ft",
		scores: [15, 10, 13, 2, 11, 7],
		saves: [4, "", "", "", "", ""],
		passivePerception: 10,
		challengeRating: "1/8",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Hooves",
			ability: 1,
			damage: [1, 4, "bludgeoning"],
			range: "Melee (5 ft)",
		}],
	},
	"pteranodon": {
		name: "Pteranodon",
		source: [["SRD24", 359], ["M24", 367]],
		size: 3,
		type: "Beast",
		subtype: "Dinosaur",
		alignment: "Unaligned",
		ac: 13,
		hp: 13,
		hd: [3, 8],
		speed: "10 ft, fly 60 ft",
		scores: [12, 15, 10, 2, 9, 5],
		skills: {
			"perception": 1,
		},
		passivePerception: 11,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Flyby",
			description: "The [THIS] doesn't provoke an Opportunity Attack when it flies out of an enemy's reach.",
		}],
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, 8, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"rat": {
		name: "Rat",
		source: [["SRD24", 359], ["M24", 367]],
		size: 5,
		type: "Beast",
		companion: ["familiar"],
		alignment: "Unaligned",
		ac: 10,
		hp: 1,
		hd: [1, 4],
		speed: "20 ft, climb 20 ft",
		scores: [2, 11, 9, 2, 10, 4],
		skills: {
			"perception": 2,
		},
		senses: "Darkvision 30 ft",
		passivePerception: 12,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Agile",
			description: "The [THIS] doesn't provoke Opportunity Attacks when it moves out of an enemy's reach.",
		}],
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, "", "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"raven": {
		name: "Raven",
		nameAlt: ["Crow"], // from Waterdeep: Dungeon of the Mad Mage
		source: [["SRD24", 359], ["M24", 368]],
		size: 5,
		type: "Beast",
		companion: ["familiar"],
		alignment: "Unaligned",
		ac: 12,
		hp: 2,
		hd: [1, 4],
		speed: "10 ft, fly 50 ft",
		scores: [2, 14, 10, 5, 13, 6],
		skills: {
			"perception": 3,
		},
		passivePerception: 13,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Mimicry",
			description: "The [THIS] can mimic simple sounds it has heard, such as a whisper or chitter. A hearer can discern the sounds are imitations with a successful DC 10 Wisdom (Insight) check.",
		}],
		attacks: [{
			name: "Beak",
			ability: 2,
			damage: [1, "", "piercing"],
			range: "Melee (5 ft)",
			abilitytodamage: false,
		}],
	},
	"reef shark": {
		name: "Reef Shark",
		nameAlt: ["Shark, Reef"],
		nameThis: "shark",
		source: [["SRD24", 360], ["M24", 368]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 22,
		hd: [4, 8],
		speed: "5 ft, swim 30 ft",
		scores: [14, 15, 13, 1, 10, 4],
		skills: {
			"perception": 2,
		},
		senses: "Blindsight 30 ft",
		passivePerception: 12,
		challengeRating: "1/2",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Pack Tactics",
			description: "The [THIS] has Advantage on an attack roll against a creature if at least one of the [THIS]'s allies is within 5 ft of the creature and the ally doesn't have the Incapacitated condition.",
		}, {
			name: "Water Breathing",
			description: "The [THIS] can breathe only underwater.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [2, 4, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"rhinoceros": {
		name: "Rhinoceros",
		source: [["SRD24", 360], ["M24", 368]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 45,
		hd: [6, 10],
		speed: "40 ft",
		scores: [21, 8, 15, 2, 12, 6],
		passivePerception: 11,
		challengeRating: "2",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Gore",
			description: "If the target is a Large or smaller creature and the [THIS] moved at least 20 ft straight toward it immediately before the hit, the target takes an extra 2d8 Piercing damage and has the Prone condition.",
		}],
		attacks: [{
			name: "Gore",
			ability: 1,
			damage: [2, 8, "piercing"],
			range: "Melee (5 ft)",
			description: "If moved 20 ft and hit \u2264Large: +2d8 damage \x26 knocked Prone",
		}],
	},
	"riding horse": {
		name: "Riding Horse",
		nameAlt: ["Horse, Riding", "Horse"],
		nameThis: "horse",
		source: [["SRD24", 360], ["M24", 368]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 13,
		hd: [2, 10],
		speed: "60 ft",
		scores: [16, 13, 12, 2, 11, 7],
		passivePerception: 10,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Hooves",
			ability: 1,
			damage: [1, 8, "bludgeoning"],
			range: "Melee (5 ft)",
		}],
	},
	"saber-toothed tiger": {
		name: "Saber-Toothed Tiger",
		nameAlt: ["Tiger, Saber-Toothed"],
		nameThis: "tiger",
		source: [["SRD24", 360], ["M24", 369]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 52,
		hd: [7, 10],
		speed: "40 ft",
		scores: [18, 17, 15, 3, 12, 8],
		saves: [6, 5, "", "", "", ""],
		skills: {
			"perception": 5,
			"stealth": 7,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 15,
		challengeRating: "2",
		proficiencyBonus: 2,
		attacksAction: 2,
		traits: [{
			name: "Running Leap",
			description: "With a 10-ft running start, the [THIS] can Long Jump up to 25 ft.",
		}],
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Rend attacks.",
		}, {
			name: "Nimble Escape",
			description: "The [THIS] can take the Disengage or Hide action as a Bonus Action.",
		}],
		attacks: [{
			name: "Rend",
			ability: 1,
			damage: [2, 6, "slashing"],
			range: "Melee (5 ft)",
			description: "Two Rend attacks as an Action",
		}],
	},
	"scorpion": {
		name: "Scorpion",
		source: [["SRD24", 360], ["M24", 369]],
		size: 5,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 1,
		hd: [1, 4],
		speed: "10 ft",
		scores: [2, 11, 8, 1, 8, 2],
		senses: "Blindsight 10 ft",
		passivePerception: 9,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Sting",
			ability: 2,
			damage: [1, "", "piercing"],
			range: "Melee (5 ft)",
			description: "+1d6 Poison damage",
		}],
	},
	"seahorse": {
		name: "Seahorse",
		source: [["SRD24", 361], ["M24", 369]],
		size: 5,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 1,
		hd: [1, 4],
		speed: "5 ft, swim 20 ft",
		scores: [1, 12, 8, 1, 10, 2],
		skills: {
			"perception": 2,
			"stealth": 5,
		},
		passivePerception: 12,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 0,
		traits: [{
			name: "Water Breathing",
			description: "The [THIS] can breathe only underwater.",
		}],
		actions: [{
			name: "Bubble Dash",
			description: "As an Action while underwater, the [THIS] moves up to its Swim Speed without provoking Opportunity Attacks.",
		}],
		attacks: [],
	},
	"spider": {
		name: "Spider",
		source: [["SRD24", 361], ["M24", 369]],
		size: 5,
		type: "Beast",
		companion: ["familiar"],
		alignment: "Unaligned",
		ac: 12,
		hp: 1,
		hd: [1, 4],
		speed: "20 ft, climb 20 ft",
		scores: [2, 14, 8, 1, 10, 2],
		skills: {
			"stealth": 4,
		},
		senses: "Darkvision 30 ft",
		passivePerception: 10,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Spider Climb",
			description: "The [THIS] can climb difficult surfaces, including along ceilings, without needing to make an ability check.",
		}, {
			name: "Web Walker",
			description: "The [THIS] ignores movement restrictions caused by webs, and the [THIS] knows the location of any other creature in contact with the same web.",
		}],
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, "", "piercing"],
			range: "Melee (5 ft)",
			description: "+1d4 Poison damage",
			abilitytodamage: false,
		}],
	},
	"tiger": {
		name: "Tiger",
		nameAlt: ["Snow Leopard", "Leopard, Snow"], // from Tales from the Yawning Portal
		source: [["SRD24", 363], ["M24", 371]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 13,
		hp: 30,
		hd: [4, 10],
		speed: "40 ft",
		scores: [17, 16, 14, 3, 12, 8],
		skills: {
			"perception": 3,
			"stealth": 7,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 13,
		challengeRating: "1",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Nimble Escape",
			description: "The [THIS] can take the Disengage or Hide action as a Bonus Action.",
		}],
		attacks: [{
			name: "Rend",
			ability: 1,
			damage: [2, 6, "slashing"],
			range: "Melee (5 ft)",
			description: "Large or smaller creature is knocked Prone",
		}],
	},
	"triceratops": {
		name: "Triceratops",
		source: [["SRD24", 363], ["M24", 372]],
		size: 1,
		type: "Beast",
		subtype: "Dinosaur",
		alignment: "Unaligned",
		ac: 14,
		hp: 114,
		hd: [12, 12],
		speed: "50 ft",
		scores: [22, 9, 17, 2, 11, 5],
		passivePerception: 10,
		challengeRating: "5",
		proficiencyBonus: 3,
		attacksAction: 2,
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make two Gore attacks.",
		}, {
			name: "Gore",
			description: "If the target is Huge or smaller and the [THIS] moved at least 20 ft straight toward it immediately before the hit, the target takes an extra 2d8 Piercing damage and has the Prone condition.",
		}],
		attacks: [{
			name: "Gore",
			ability: 1,
			damage: [2, 12, "piercing"],
			range: "Melee (5 ft)",
			description: "If moved 20 ft and hit \u2264Huge: +2d8 damage \x26 knocked Prone; Two Gore attacks as an Action",
		}],
	},
	"tyrannosaurus rex": {
		name: "Tyrannosaurus Rex",
		nameAlt: ["T-Rex"],
		nameThis: "T-Rex",
		source: [["SRD24", 363], ["M24", 372]],
		size: 1,
		type: "Beast",
		subtype: "Dinosaur",
		alignment: "Unaligned",
		ac: 13,
		hp: 136,
		hd: [13, 12],
		speed: "50 ft",
		scores: [25, 10, 19, 2, 12, 9],
		saves: [10, "", "", "", 4, ""],
		skills: {
			"perception": 4,
		},
		passivePerception: 14,
		challengeRating: "8",
		proficiencyBonus: 3,
		attacksAction: 2,
		addMod: [{
			type: "skill", field: "Init", mod: "Prof",
			text: "The tyrannosaurus adds its Proficiency Bonus to its Initiative rolls.",
		}],
		actions: [{
			name: "Multiattack",
			description: "As an Attack action, the [THIS] can make one Bite attack and one Tail attack.",
		}, {
			name: "Bite",
			description: "If the target is a Large or smaller creature, it has the Grappled condition (escape DC 17). While Grappled, the target has the Restrained condition and can't be targeted by the [THIS]'s Tail.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [4, 12, "piercing"],
			range: "Melee (10 ft)",
			description: "\u2264Large is Grappled (escape DC 17); Restrained while Grappled",
		}, {
			name: "Tail",
			ability: 1,
			damage: [4, 8, "bludgeoning"],
			range: "Melee (15 ft)",
			description: "Huge or smaller creature is knocked Prone",
		}],
	},
	"venomous snake": {
		name: "Venomous Snake",
		nameAlt: ["Snake, Venomous"],
		nameThis: "snake",
		source: [["SRD24", 363], ["M24", 372]],
		size: 5,
		type: "Beast",
		companion: ["pact_of_the_chain"],
		alignment: "Unaligned",
		ac: 12,
		hp: 5,
		hd: [2, 4],
		speed: "30 ft, swim 30 ft",
		scores: [2, 15, 11, 1, 10, 3],
		senses: "Blindsight 10 ft",
		passivePerception: 10,
		challengeRating: "1/8",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, 4, "piercing"],
			range: "Melee (5 ft)",
			description: "+1d6 Poison damage",
		}],
	},
	"vulture": {
		name: "Vulture",
		nameAlt: ["Peacock"], // from Baldur's Gate: Descend into Avernus
		source: [["SRD24", 363], ["M24", 372]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 10,
		hp: 5,
		hd: [1, 8],
		speed: "10 ft, fly 50 ft",
		scores: [7, 10, 13, 2, 12, 4],
		skills: {
			"perception": 3,
		},
		passivePerception: 13,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Pack Tactics",
			description: "The [THIS] has Advantage on an attack roll against a creature if at least one of the [THIS]'s allies is within 5 ft of the creature and the ally doesn't have the Incapacitated condition.",
		}],
		attacks: [{
			name: "Beak",
			ability: 2,
			damage: [1, 4, "piercing"],
			range: "Melee (5 ft)",
		}],
	},
	"warhorse": {
		name: "Warhorse",
		nameAlt: ["Horse, War"],
		nameThis: "horse",
		source: [["SRD24", 364], ["M24", 373]],
		size: 2,
		type: "Beast",
		alignment: "Unaligned",
		ac: 11,
		hp: 19,
		hd: [3, 10],
		speed: "60 ft",
		scores: [18, 12, 13, 2, 12, 7],
		saves: ["", "", "", "", 3, ""],
		passivePerception: 11,
		challengeRating: "1/2",
		proficiencyBonus: 2,
		attacksAction: 1,
		actions: [{
			name: "Hooves",
			description: "If the target is a Large or smaller creature and the horse moved at least 20 ft straight toward it immediately before the hit, the target takes an extra 2d4 Bludgeoning damage and has the Prone condition.",
		}],
		attacks: [{
			name: "Hooves",
			ability: 1,
			damage: [2, 4, "bludgeoning"],
			range: "Melee (5 ft)",
			description: "If moved 20 ft and hit \u2264Large: +2d4 damage \x26 knocked Prone",
		}],
	},
	"weasel": {
		name: "Weasel",
		source: [["SRD24", 364], ["M24", 372]],
		size: 5,
		type: "Beast",
		companion: ["familiar"],
		alignment: "Unaligned",
		ac: 13,
		hp: 1,
		hd: [1, 4],
		speed: "30 ft, climb 30 ft",
		scores: [3, 16, 8, 2, 12, 3],
		skills: {
			"acrobatics": 5,
			"perception": 3,
			"stealth": 5,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 13,
		challengeRating: "0",
		proficiencyBonus: 2,
		attacksAction: 1,
		attacks: [{
			name: "Bite",
			ability: 2,
			damage: [1, "", "piercing"],
			range: "Melee (5 ft)",
			abilitytodamage: false,
		}],
	},
	"wolf": {
		name: "Wolf",
		nameAlt: ["Sled Dog", "Dog, Sled"], // from Rise of Tiamat
		source: [["SRD24", 364], ["M24", 373]],
		size: 3,
		type: "Beast",
		alignment: "Unaligned",
		ac: 12,
		hp: 11,
		hd: [2, 8],
		speed: "40 ft",
		scores: [14, 15, 12, 3, 12, 6],
		skills: {
			"perception": 5,
			"stealth": 4,
		},
		senses: "Darkvision 60 ft",
		passivePerception: 15,
		challengeRating: "1/4",
		proficiencyBonus: 2,
		attacksAction: 1,
		traits: [{
			name: "Pack Tactics",
			description: "The [THIS] has Advantage on attack rolls against a creature if at least one of the [THIS]'s allies is within 5 ft of the creature and the ally doesn't have the Incapacitated condition.",
		}],
		attacks: [{
			name: "Bite",
			ability: 1,
			damage: [1, 6, "piercing"],
			range: "Melee (5 ft)",
			description: "Medium or smaller creature is knocked Prone",
		}],
	},
};
